---
latitude: 59.68634
longitude: 18.7806
map_zoom: 12
name: Marholmen Stugor
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: Marholmen 1
  street2: ''
  state: ''
  city: Norrtalje
  country: 
  zip_code: '76197'
_hotel_id: MAR341
_portal_id: required-but-empty
_root_path: http://rtexpress-qa.ttaws.com/rt/.
